### ISSUE TITLE
quick comments re Contributing

### ISSUE THREAD

**Issue by cboettig** [ropensci/dotgithubfiles#1]
Should the README or something note that Contributing is specific to ropensci? (it isn't really, other than the link to our discourse page, which means some people might adopt it with non-ropensci packages).

Should contributors be encouraged to file an issue discussing the proposed PR first? (excepting PRs to fix such things as documentation)?

**Comment by sckott** [comment]
Yeah, good idea about clarifying in the README. Will do that. 

Yeah, i think we should encourage an issue first.

**Comment by sfirke** [comment]
The README says:

> Update the issue_template.md file with the github owner (e.g., ropensci) and repo name (e.g., foobar).

I think that should be:

> Update the CONTRIBUTING.md file with the github owner (e.g., ropensci) and repo name (e.g., foobar).

**Comment by sckott** [comment]
good catch @sfirke , will fix
