### ISSUE TITLE
update the templates before inclusion in rodev

### ISSUE THREAD

**Issue by maelle** [ropensci/dotgithubfiles#6]
- [x]  Make a PR to this repo with new versions of the templates
- [x]   Put them in a dotgithub folder cf #3 
- [x]   Use them in a rodev helper function (because usethis templating functions mentioned in #4 don't exist yet I think?)
- [x]  Mention the templates and function in dev_guide

**Comment by maelle** [comment]
@sckott regarding "inclusion in rodev": in that package I'll have a function using `usethis::use_template` so I'd like the templates to live in inst/ in that repo. We could either

* have them both here and there

* not have them here, only have the README here with link to the templates in rodev/inst?

**Comment by maelle** [comment]
I'll close this issue once the question above about where to keep the files is answered.

**Comment by sckott** [comment]
i like having a canonical place for the files, and not everyone will use an R package to get them, so maybe makes sense to have them in both

**Comment by maelle** [comment]
Ok!
